### PR TITLE
Add cosri tabs config

### PR DESCRIPTION
**Pull request by ivan-c**
Add config examples for UWMC systems (where FHIR pipeline is enabled) 

see uwcirg/cosri-pain-management-summary/pull/152

### CODE REVIEW

**Comment by ivan-c** [comment]
@achen2401 
I was trying to think how to best group the site-specific configs (for uwmc/skagit/kent etc). We don't need to make any changes now, but I'd like to talk it through with you and see if I'm missing anything.

I was thinking it might make sense to fold these config values under the `REACT_APP_SITE_ID`? ie automatically enable these configs when `REACT_APP_SITE_ID=UWMC`

**Comment by achen2401** [comment]
> 
> I was thinking it might make sense to fold these config values under the `REACT_APP_SITE_ID`? ie automatically enable these configs when `REACT_APP_SITE_ID=UWMC`

@ivan-c so instead of having new config variable `REACT_APP_TABS` (The config var, `REACT_APP_SCORING_INSTRUMENTS` is actually not being used now), I can just make use of `REACT_APP_SITE_ID` config?
So for instance [here](https://github.com/uwcirg/cosri-pain-management-summary/blob/develop/src/helpers/utility.js#L626), it can just return `getEnv("REACT_APP_SITE_ID") === UWMC` ?

**Comment by ivan-c** [comment]
> I can just make use of the existing`REACT_APP_SITE_ID` config?

Yup, at least if it makes sense. UWMC is the only site with these features at the moment, but wasn't sure if the more granular config was helpful for dev etc

**Comment by ivan-c** [comment]
> I can just make use of the existing`REACT_APP_SITE_ID` config?

@achen2401 

Yup, at least if it makes sense. UWMC is the only site with these features at the moment, but wasn't sure if the more granular config was helpful for dev etc

**Comment by achen2401** [comment]
@ivan-c that makes sense and makes things easier and cleaner.  Here is my PR for the changes: https://github.com/uwcirg/cosri-pain-management-summary/pull/158

**Comment by ivan-c** [comment]
Thank you Amy!! Closing this since it's no longer required

**Pull request closed without merging**
